title: <p align="center"> Amitesh Pandey </p>
logo: /assets/img/amiteshImage.PNG
description:
<p align="center">
  <a href="https://www.linkedin.com/in/amiteshpandey-1992/">LinkedIn</a> |
  <a href="https://github.com/amitesh-pandey">GitHub</a>
<br>
A data science enthusiast with 4+ years of overall experience as Technical Engineer in different domain and 2+ years of experience as ML engineer & Research data scientist. Proficient in building mathematical and Statistical data analytics, and predictive modelling, Machine Learning, Deep Learning, python. Experienced in Python programming for 3+ years. Delivered 40+ technical lectures on Data Science, Software Defined Radio and Single Board Computers. Strong
understanding of interpreting and analysing data to drive successful business solutions.
<br>
</p>

theme: jekyll-theme-minimal
