title: <p align="center"> Amitesh Pandey </p>
logo: /assets/img/amiteshImage.PNG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/amiteshpandey-1992/">LinkedIn</a> |
  <a href="https://github.com/amitesh-pandey">GitHub</a><br>

  Working as Research Data Scientist in Sequretek IT Solutions Pvt Ltd. Proficient in building Mathematical, Statistical Data Analytics and Predictive Modelling, Machine Learning, Deep Learning.<br>
  </p>
  
theme: jekyll-theme-minimal

  
