title: <p align="center"> Amitesh Pandey </p>
logo: /assets/img/amiteshImage.PNG
description:
<p align="center">
<a href="https://www.linkedin.com/in/amiteshpandey-1992/">LinkedIn</a> |
<a href="https://github.com/amitesh-pandey">GitHub</a>

<br>
A Data Science enthusiast with 4+ years of overall experience in Tech Industries with 2+ years of experience as Research data scientist. Proficient in building mathematical, Statistical data analytics and predictive modelling, Machine Learning, Deep Learning. Delivered 40+ technical lectures on Data Science, Software Defined Radio and Single Board Computers.
<br>
</p>

theme: jekyll-theme-minimal
